### ISSUE TITLE
is `a :PersonName` needing to be inferred?

### ISSUE THREAD

**Issue by xristy** [buda-base/git-to-dbs#9]
In [blmp commit 65a22702](https://github.com/BuddhistDigitalResourceCenter/blmp-prototype-flow/commit/65a22702542ba48662d6b1d07537fe995dd987a5) Nicolas asks:

> idem why the redundant ':PersonName [ a :PersonName, :PersonCommonName ; rdfs:label "klong chen pa/"@bo-x-ewts ]' ?

After thinking on it to make a reply I came to the conclusion that I had no good reason for it to be inferred. It seems to me that typical usage will be like:

    select ?s ?type ?nm
    where {
       ?s :personName ?b .
       ?b a ?type .
       ?b rdfs:label ?nm .
       filter ( ?type != :PersonName )
    }

since we will generally want the specific type of name and the fact that `:personName` is being used to select the blank node already implies `[] a :PersonName`.

The filter becomes unnecessary if `[] a :PersonName` is not inferred.

wdyt?

**Comment by MarcAgate** [comment]
Hi,
This is a general pattern we also encounter with PersontEvent,
PlaceEvent and so on and  I use the same stratagem (Filtering out the
superclass Type) in my queries.
I tried to use property path like below, thinking it would be great to
have the possibility to query directly for rdfs:label of instances of
the subclasses of PersonName: 
?x :personName ?blank.?blank rdf:type/rdfs:subClassOf* ?subclass .
but it turns out that in ontologies, a class is considered a subclass
of itself, so PersonName is a subclass of PersonName and there's still
the need to filter it out.

Marc
Le samedi 20 janvier 2018 à 10:00 -0800, Chris Tomlinson a écrit :

**Comment by xristy** [comment]
The inferSubtree has been removed for :PersonName, :PersonEvent, :PlaceEvent and :WorkTitle. The  triple store on buda1 is being rebuilt now and should be completed by 11:00 US.CST
